### ISSUE TITLE
Web interface only works one way

### ISSUE THREAD

**Issue by PowerFPV** [yagiziskirik/Kerbal-Telemetry#8] opened 2021-06-28 07:44 UTC
After following setup instructions as per github, I can successfuly connect to the web interface. I can press the staging button, which will activate staging in the game.
However, only the default data is displayed - it does not update or change
![image](https://user-images.githubusercontent.com/58056352/123598732-2a0a0500-d838-11eb-9ed4-1af2e24b4472.png)

I tried changing my mechjeb version from the latest to 2.9.2.0 and a few others, but this didn't change any behaviour sadly.
I have also tried making firewall rules to let the program out, but didn't help either.

In game, I can see on kRPC that the clients are connected fine.
![image](https://user-images.githubusercontent.com/58056352/123599024-76eddb80-d838-11eb-998a-5a0f0bac8075.png)

Any help would be greatly appreciated!

**Comment by yagiziskirik** [comment] 2021-06-28 08:14
Hello @PowerFPV,

Thank you for reporting this issue. kRPC and other extensions are for the staging and flight commands section. The problem could be caused by 3 factors as far as I experienced: It could be python server (It is the window that opens when you start Kerbal Telemetry), DLL file (you can check that as well from the KSP console via `Alt + F12`) or unknown character errors.

We can start the diagnosis with the data.json file. It is under the Kerbal Telemetry/static folder. But it is probably containing the exact values that you see on the web interface. You can check the Python console, but I am almost sure there wouldn't be any serious errors either. These two are the most common options. You can check the KSP console as I described, maybe we see an error code there.

Also, would you tell me which platform that you downloaded it from? And did you set it up manually? Because another common issue is the file and folder order. Under the GameData folder, there should be a `Kerbal Telemetry` folder and a `Kerbal Telemetry.dll` file separately. If I know the facts of these unknowns, I can assist you further.

**Comment by PowerFPV** [comment] 2021-06-28 08:29
Thanks for the prompt reply!

The Python console seems to just be a constant loop of GET 
![image](https://user-images.githubusercontent.com/58056352/123604248-047ffa00-d83e-11eb-9e39-4756cdd772f9.png)
This continues to update, which I would assume is normal as it tries to pull data.

I had a look at the data.json file. After launching a ship and then pausing, it matches up with data in KSP - the altitude, ship name, everything is correct. These are the correct values that should be on the web interface!
![image](https://user-images.githubusercontent.com/58056352/123604959-b15a7700-d83e-11eb-9b58-f28bd6518a55.png)


I have downloaded everything I'm using from GitHub, and followed instructions as per this GitHub repo's guide. Folder structure is correct.

**Comment by yagiziskirik** [comment] 2021-06-28 08:42
Well, the Python console looks perfectly fine, and we have a working data extraction from KSP. Then all the arrows point to the web interface. Can you look at the browser console as well? You can use [this](https://balsamiq.com/support/faqs/browserconsole/) link to open your browser console if you don't know how to do it for your browser. You can clear the website cache as well, it sometimes solves the problem since some errors caused by old version data overlapping the new update.

**Comment by PowerFPV** [comment] 2021-06-28 08:52
Cleared website cache, no luck sadly. I tried Chrome, Firefox and even Edge but all the same. Looking at web browser console, I get these reports 
![image](https://user-images.githubusercontent.com/58056352/123608186-e3b9a380-d841-11eb-936c-0e22dfb69b45.png)
Sadly I'm not knowledgeable in anything java, python or the like so not sure if these errors are generic web ones or related to the issue. Firefox console shows the same errors.

**Comment by yagiziskirik** [comment] 2021-06-28 09:11
Somewhere inside the `data.json` file, there *can* be an error. But interestingly, there is no sign of an issue for now. Can you copy-paste the `data.json` file so I can take a look at it? Sorry for bothering you so much, I don't know the exact issue so I cannot recreate it on my own machine.

**Comment by PowerFPV** [comment] 2021-06-28 09:21
Thanks so much for your help! Here is the data.json, taken from a paused flight just shortly after launch. Wasn't able to attatch to github sadly, it reckons the file isn't supported?
`{"altitude":287.017507217941,"distanceTraveled":128.364892045583,"externalTemperature":30.4915478079399,"GForce":2.6864028710914,"canComm":"TRUE","situation":"Flying Low","timeToPe":284.093129347382,"lat":-0.0979980567502214,"lon":-74.5608291102572,"verticalSpeed":78.9766656163818,"missionTime":8.78000000817701,"speed":78.7621383666992,"name":"Pegasus 1","atmDensity":1.11632853200913,"currentStage":7,"deltaV":2341.75399780273,"timeToAp":8.09873137669058,"orbitSpeed":177.840940186048,"orbitIncl":1.23246732979071,"orbitEcc":0.995686664469096,"ApA":596.947918774793,"PeA":-598701.912378665,"horizSpeed":16.0841034110084,"partCount":63,"mass":96.0962896159617,"acceleration":16.6975945589751,"convFlux":255.374728808378,"radFlux":-15.3291113033998,"intFlux":32395.4407289728,"planetName":"Kerbin","yaw":258.693542480469,"pitch":81.9373779296875,"roll":-107.425117492676,"coolTemp":25.1285170099669,"coolSkinTemp":25.1914393271723,"coolSkinName":"SuperDraco Engine","hotTemp":41.2851518118914,"hotSkinTemp":32.2520552625437,"hotSkinName":"S3 KS-25 \"Vector\" Liquid Fuel Engine","critTemp":25.3298763703322,"critSkinTemp":27.43103765322,"critSkinName":"Aerocam","targetName":"NON","distance":0,"targetSpeed":0,"targetLat":0,"targetLong":0}`

If there is anything at all I can do to help you solve this, I am more than happy to oblige! I very much appreciate it :)

**Comment by yagiziskirik** [comment] 2021-06-28 09:32
<img width="1440" alt="SS" src="https://user-images.githubusercontent.com/33431578/123613724-5a3bae80-d80c-11eb-8a43-23fc17a48da8.png">
I copy-pasted your code and you can see that data shown up on the web interface. There is nothing wrong with the `data.json` file or the .dll file. I will try to figure out what can I do and I will brief you shortly. Thank you for your patience.

**Comment by MekoNix** [comment] 2021-06-28 10:31
I faced such problem. The solution was to delete the mod folder and reinstall the game. You can simply delete the mod, start the game and reinstall the mod.

**Comment by yagiziskirik** [comment] 2021-06-28 14:33
You can try @MekoNix's solution idea and check that if it works for now. I am trying to find a general solution since I am not the "reinstall until it works" kind of developer, I will find a way to fix it properly. I installed the game and the mod on four different machines and still couldn't recreate the issue. Tell me if you see an error message of any sort. I developed an error catching algorithm to catch every message. I will polish it and send it to you from here, and we can check if there are any problems that we couldn't see.

**Comment by yagiziskirik** [comment] 2021-07-13 10:31
Since you have not replied for a while, I will close the issue right now. If you encounter the same issue again, please do not hesitate to tell.

**Closed by yagiziskirik** 2021-07-13 10:31 UTC
